### ISSUE TITLE
When the temperature drops below zero, the component returns 0

### ISSUE THREAD

**Issue by ionel-dragomirescu** [ElectronicCats/ElectronicCats_InternalTemperatureZero#10]
Hello,

I noticed that when the temperature drops below 0 degrees, the component returns the value 0.
Is it a sensor limitation in the processor or a component bug?

Thank you very much,
Ionel

**Comment by xpeqex** [comment]
Hi @ionel-dragomirescu

**Comment by xpeqex** [comment]
Hi @ionel-dragomirescu 

I apologize for the bot activation and appreciate your patience.

In order to understand your issue in a better way, can you tell me what microcontroller are you trying to use with our library?
With this information, I will be able to give you accurate information.

Hope you are having a nice day!

**Comment by ionel-dragomirescu** [comment]
Hi,
I try to using library with Microcontroller ATSAMD21G18, 32-Bit ARM Cortex M0+.
Thank you,
BR Ionel

**Comment by xpeqex** [comment]
Thank you @ionel-dragomirescu for the info.

I will be testing this and I will keep you updated with any news.

Merry Christmas! 🎄

**Comment by xpeqex** [comment]
Hi @ionel-dragomirescu 

Could you please indicate to me which example of the library are you using or if you modified it?

I have been trying to replicate this problem with the same microcontroller and the BasicTemperature example, however, on all occasions, negative temperatures were displayed on the serial monitor when the temperature is below 0C. Here is a screenshot of it:

![Screenshot_2022-12-26_12 45 40_PM](https://user-images.githubusercontent.com/107638696/209581980-d102208a-b544-4713-8e30-a56160d84b2b.png)

**Comment by ionel-dragomirescu** [comment]
Hi [xpeqex](https://github.com/xpeqex)

I did multiple tests and noticed that it doesn't "measure" well in the 0-1C range. I searched further and discovered a bug when saving and displaying this range.

The library is doing well, so we can close the case.
Thank you and I apologize for the inconvenience,
BR, Ionel

**Comment by xpeqex** [comment]
Thank you for updating us @ionel-dragomirescu 

I will close this issue now, there is no inconvenience at all!

Have a happy new year 🎉
