### ISSUE TITLE
seeeduino xiao reads wrong temperature

### ISSUE THREAD

**Issue by david3a** [ElectronicCats/ElectronicCats_InternalTemperatureZero#9]
I'm getting values of aroudn -171C at room temperature, after looking at values read from adc I ficn that I get values around 958 not around 2800 as I get when working, occasionally it comes up correct which is odd

i'd modified the read code to do this

   // do range check
   if( adcReading < 2000 )
   {
    if( _debugSerial )
      _debugSerial->printf("bodging reading as less tha 2000 was %d to %d\n", adcReading, adcReading * 3);
    adcReading *= 3;
   }

and now all seems well, not comfortable with this as a solution but not sure where to look. Thought it might be the circuit but as it does read correctly some times it seems less likely.

any ideas?

**Comment by xpeqex** [comment]
Hi @david3a 

Thank you for contacting us!

Could you please help indicate which specific code/file are you modifying?

**Comment by david3a** [comment]
TemperatureZero.cpp : 154

**Comment by david3a** [comment]
May well raise a pull request as well for something, do you consider them?

David

**Comment by xpeqex** [comment]
@david3a Thank you for letting me know the code you are using.
We would like to ask you for the following additional information:

- Which board are you using?
- What Operating System and version are you using (e.g., Windows 11, macOS 12.0, Linux)?
- Which IDE are you using to program the board?
- Which are your diagram/connections?

**Comment by david3a** [comment]
Seeeduino xiao
Windows 11
Vs code and platform io

Its internal!

**Comment by xpeqex** [comment]
Hi @david3a 

I've been testing the library on several supported boards and it's working fine, is it possible to you to test a different dev board to verify that is not a hardware issue?

**Comment by david3a** [comment]
Not easily as it’s the module we use!

I have  hack that gets around it, will go with that for the moment

David

**Comment by xpeqex** [comment]
Hi @david3a 

Since this issue was replicated without the same result as you are facing, we recommend you try with a different board, IDE, or using the examples included in the repository, also, since this problem is not recurrent we will close the ticket.

Hope you are having a nice day!
